### ISSUE TITLE
Saving voice

### ISSUE THREAD

**Issue by moh1122** [machuiwen/Pitch-Perfect-iOS9#1]
Hello thanks for the great app
btw is there a way to save the voices.
Thank you

**Comment by machuiwen** [comment]
Yes the latest version already supports that

**Comment by moh1122** [comment]
Really, i just downloaded the latest version and it only plays the recorded sound when i put back and record again it overwrites it ?

**Comment by machuiwen** [comment]
Oh, you mean save the voices of the former recording? You may need to save them as different names, and use some container to store those names for retrieval.

**Comment by moh1122** [comment]
yep
can you show me how please ?
